### ISSUE TITLE
TestInstMemPython fails intermittenly

### ISSUE THREAD

**Issue by grantslape** [grantslape/CS3339-MIPS32#74]
The build fails unit test TestInstMemPython seemingly randomly.  This is difficult to reproduce, which seems to be caused by the PRNG not being seeded in a consistent manner. 

```
======================================================================
ERROR: testInstMemDynamicPython (test.test_inst_mem.TestInstructionMemory)
Testing regular operation Python
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/test/test_inst_mem.py", line 45, in testInstMemDynamicPython
    Simulation(stim, self.dut).run(quiet=1)
  File "/usr/local/lib/python3.6/site-packages/myhdl/_Simulation.py", line 152, in run
    waiter.next(waiters, actives, exc)
  File "/usr/local/lib/python3.6/site-packages/myhdl/_Waiter.py", line 172, in next
    clause = next(self.generator)
  File "/usr/local/lib/python3.6/site-packages/myhdl/_always_comb.py", line 83, in genfunc
    func()
  File "/app/src/python/inst_mem.py", line 25, in logic
    inst_out.next = raw_mem[inst_reg//4]
IndexError: list index out of range```

**Comment by grantslape** [comment]
🫡
